import { ZoneData } from '../types';

// Định nghĩa màu sắc (Lấy từ code cũ của bạn)
export const YARD_COLORS = {
  road: '#334155', // SỬA TỪ '#00BFFF' (Xanh ngọc) THÀNH '#334155' (Xám đen)
  roadDark: '#1e293b', // Xám đen đậm hơn cho đường chính
  wharf: '#E6B8B7', 
  blockGreen: '#92D050', 
  blockCyan: '#00FFFF', 
  blockOrange: '#FFC000', 
  warehouseGray: '#D9D9D9', 
  buildingOrange: '#F4B084', 
  grass: '#70AD47', 
  gate: '#FFFF00', 
  rfBlue: '#002060', 
  text: '#000000',
};

export const ZONES: ZoneData[] = [
  // --- ROADS ---
  {
    id: 'road-main-vertical',
    label: 'ĐƯỜNG CHUYỂN LINE',
    type: 'road',
    position: [0, 0.05, 0],
    size: [8, 0.1, 160], 
    color: YARD_COLORS.roadDark,
    traffic: 'Heavy',
  },
  {
    id: 'road-vertical-right',
    label: 'ĐƯỜNG DẪN RF3',
    type: 'road',
    position: [75, 0.05, -17.5], 
    size: [8, 0.1, 145], 
    color: YARD_COLORS.roadDark,
    traffic: 'Normal',
  },
  {
    id: 'road-vertical-inner-left',
    label: 'ĐƯỜNG DẪN CÂN 1',
    type: 'road',
    position: [-60, 0.05, -17.5], 
    size: [6, 0.1, 145], 
    color: YARD_COLORS.roadDark,
    traffic: 'Normal',
  },
  {
    id: 'road-wharf',
    label: 'ĐƯỜNG CẦU TÀU',
    type: 'road',
    position: [0, 0.05, -90],
    size: [800, 0.1, 15], 
    color: YARD_COLORS.roadDark,
    traffic: 'Heavy',
  },
  {
    id: 'road-cross-1',
    label: 'Đường D1',
    type: 'road',
    position: [0, 0.05, -45], 
    size: [100, 0.1, 6],
    color: YARD_COLORS.road,
    traffic: 'Light',
  },
  {
    id: 'road-cross-2',
    label: 'Đường D2',
    type: 'road',
    position: [0, 0.05, -15], 
    size: [100, 0.1, 6],
    color: YARD_COLORS.road,
    traffic: 'Normal',
  },
  {
    id: 'road-cross-3',
    label: 'Đường D3',
    type: 'road',
    position: [0, 0.05, 15], 
    size: [100, 0.1, 6],
    color: YARD_COLORS.road,
    traffic: 'Normal',
  },
  {
    id: 'road-bottom',
    label: 'ĐƯỜNG CỔNG',
    type: 'road',
    position: [0, 0.05, 55], 
    size: [350, 0.1, 8], 
    color: YARD_COLORS.road,
    traffic: 'Heavy',
  },
  {
    id: 'road-connector-in',
    label: 'ĐƯỜNG VÀO',
    type: 'road',
    position: [-105, 0.05, 75], 
    size: [20, 0.1, 45],
    color: YARD_COLORS.road,
    traffic: 'Heavy',
  },
  {
    id: 'road-connector-out',
    label: 'ĐƯỜNG RA',
    type: 'road',
    position: [115, 0.05, 75], 
    size: [20, 0.1, 45],
    color: YARD_COLORS.road,
    traffic: 'Normal',
  },

  // --- TOP AREA (WHARF) ---
  {
    id: 'wharf-area',
    label: 'KHU VỰC CẦU TÀU',
    type: 'special',
    position: [0, 0.02, -100], 
    size: [800, 0.1, 30],
    color: YARD_COLORS.wharf,
    details: ['3 Tàu hoạt động', 'Khu vực xếp dỡ'],
  },

  // --- BLOCKS ---
  {
    id: 'block-g',
    label: 'BLOCK G\nSHIFTING TÀU',
    type: 'container_export',
    position: [-35, 0.5, -65],
    size: [40, 1, 25],
    color: YARD_COLORS.blockGreen,
    details: ['Hàng shifting tàu'],
    capacity: 85,
  },
  {
    id: 'block-c',
    label: 'BLOCK C\nHÀNG XUẤT/NHẬP',
    type: 'container_export',
    position: [-35, 0.5, -30],
    size: [40, 1, 20],
    color: YARD_COLORS.blockGreen,
    details: ['Rows: 1-6'],
    capacity: 60,
  },
  {
    id: 'block-b',
    label: 'BLOCK B\nHÀNG XUẤT',
    type: 'container_export',
    position: [-35, 0.5, 0],
    size: [40, 1, 20],
    color: YARD_COLORS.blockCyan,
    details: ['Chuyên hàng xuất'],
    capacity: 75,
  },
  {
    id: 'block-a',
    label: 'BLOCK A\nKHU VỰC RỖNG',
    type: 'container_empty',
    position: [-35, 0.5, 30],
    size: [40, 1, 20],
    color: YARD_COLORS.blockGreen,
    details: ['Container rỗng'],
    capacity: 20,
  },
  {
    id: 'block-h-cont',
    label: 'BLOCK H\nCONT',
    type: 'container_import', 
    position: [25, 0.5, -65],
    size: [20, 1, 25], 
    color: YARD_COLORS.blockOrange,
    capacity: 90,
  },
  {
    id: 'block-h-warehouse',
    label: 'BLOCK H\nCFS Ô TÔ',
    type: 'warehouse', 
    position: [45, 0.5, -65],
    size: [20, 1, 25], 
    color: YARD_COLORS.blockGreen,
  },
  {
    id: 'block-f',
    label: 'BLOCK F\nHÀNG NHẬP',
    type: 'container_import',
    position: [35, 0.5, -30],
    size: [40, 1, 20],
    color: YARD_COLORS.blockOrange,
    capacity: 65,
  },
  {
    id: 'block-e',
    label: 'BLOCK E\nHÀNG NHẬP',
    type: 'container_import',
    position: [35, 0.5, 0],
    size: [40, 1, 20],
    color: YARD_COLORS.blockOrange,
    capacity: 70,
  },
  {
    id: 'block-d',
    label: 'BLOCK D\nHÀNG NHẬP',
    type: 'container_import',
    position: [35, 0.5, 30],
    size: [40, 1, 20],
    color: YARD_COLORS.blockOrange,
    capacity: 80,
  },

  // --- BUILDINGS & SPECIAL AREAS ---
  {
    id: 'tram-y-te',
    label: 'VP THỦ TỤC',
    type: 'building',
    position: [-80, 1, 15], 
    size: [10, 3, 15],
    color: '#D2B48C',
  },
  {
    id: 'tram-dien-1',
    label: 'TRẠM\nY TẾ',
    type: 'building',
    position: [-80, 2, 40], 
    size: [8, 3, 8],
    color: '#ea580c',
  },
  {
    id: 'tram-can-1',
    label: 'CẦN CÂN 01',
    type: 'building',
    position: [-80, 1, -20], 
    size: [8, 1, 20],
    color: '#ecfccb',
  },
  {
    id: 'block-k',
    label: 'BLOCK K\nCONT RỖNG',
    type: 'container_empty',
    position: [-105, 0.5, -30], 
    size: [25, 1, 70],
    color: '#CDC6A5',
    capacity: 30,
  },
  {
    id: 'rf1',
    label: 'KHU VỰC\nRF1',
    type: 'container_empty', 
    position: [-110, 0.2, 35], 
    size: [30, 0.5, 20],
    color: YARD_COLORS.rfBlue,
    details: ['Khu vực cont lạnh/sửa chữa'],
    capacity: 50,
  },
  {
    id: 'rua-cont',
    label: 'KHU VỰC\nRỬA CONT',
    type: 'container_empty', 
    position: [-150, 0.2, 35], 
    size: [30, 0.5, 20],
    color: '#e2e8f0',
    details: ['Bãi rửa container'],
    capacity: 5,
  },
  {
    id: 'cfs-area-barge',
    label: 'KHU VỰC CFS\nĐÓNG/RÚT GHE/SALAN',
    type: 'warehouse', 
    position: [-350, -1, -130], 
    size: [60, 2, 25],
    color: '#FF4500', 
    rotation: 0,
    details: ['Tiếp nhận Ghe/Salan', 'Khu vực đường thủy'],
  },
  {
    id: 'kho-04',
    label: 'KHO 04',
    type: 'warehouse',
    position: [-35, 2, 75], 
    size: [45, 6, 25],
    color: '#A8DADC',
  },
  {
    id: 'office-mr',
    label: 'KHU VỰC\nSỬA CHỮA',
    type: 'building',
    position: [0, 2, 75], 
    size: [20, 5, 25],
    color: YARD_COLORS.buildingOrange,
  },
  {
    id: 'factory',
    label: 'XÍ NGHIỆP MAY\nNHÀ BÈ',
    type: 'building',
    position: [40, 2, 75], 
    size: [50, 5, 30],
    color: YARD_COLORS.grass,
  },
  {
    id: 'rf3-cfs',
    label: 'KHU VỰC\nRF3/CFS',
    type: 'special',
    position: [80, 1, 75], 
    size: [20, 3, 30],
    color: YARD_COLORS.rfBlue,
  },
  {
    id: 'cont-tank',
    label: 'KHU VỰC\nCONT TANK',
    type: 'container_import',
    position: [145, 0.5, -40], 
    size: [20, 1, 30],
    color: YARD_COLORS.blockOrange,
    capacity: 45,
  },
  {
    id: 'tram-can-2',
    label: 'CẦN CÂN 02',
    type: 'building',
    position: [115, 1, -40],
    size: [8, 1, 20],
    color: '#ecfccb',
  },
  {
    id: 'vp-hang-nhap',
    label: 'VĂN PHÒNG\nHÀNG NHẬP',
    type: 'building',
    position: [115, 2, -10], 
    size: [12, 4, 20],
    color: YARD_COLORS.buildingOrange,
  },
  {
    id: 'tram-dien-2',
    label: 'TRẠM\nĐIỆN',
    type: 'building',
    position: [115, 2, 18], 
    size: [8, 3, 10],
    color: '#ea580c',
  },
  {
    id: 'tram-dien-2',
    label: 'RF2',
    type: 'building',
    position: [115, 2, 28], 
    size: [12, 3, 12],
    color: '#0cea40ff',
  },
];